version: "3.8"

services:
  castaccord_service:
    container_name: castaccord_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - twitch-network

networks:
  twitch-network:
    external: true