version: "3.7"
volumes:
  node_modules:
services:
  castaccord_service:
    image: castaccord-service
    build:
      context: ./
      dockerfile: Dockerfile_local
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - twitch-network

networks:
  twitch-network:
    external: true